/**
 * Action Types
 */
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_ERROR = 'AUTH_ERROR';
export const TOGGLE_MOBILE = 'TOGGLE_MOBILE';
export const SET_TOPBAR_TITLE = 'SET_TOPBAR_TITLE';
export const LOAD_DEMOS = 'LOAD_DEMOS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const NEW_DEMO = 'NEW_DEMO';
export const EDIT_DEMO = 'EDIT_DEMO';
export const EDITOR_INIT = 'EDITOR_INIT';
export const EDITOR_UPDATE_IMAGE = 'EDITOR_UPDATE_IMAGE';
export const EDITOR_NAVIGATE = 'EDITOR_NAVIGATE';
export const EDITOR_CHANGE_AFFILIATE = 'EDITOR_CHANGE_AFFILIATE';
export const EDITOR_SAVE_DATA = 'EDITOR_SAVE_DATA';
export const EDITOR_REUSE_DATA = 'EDITOR_REUSE_DATA';
export const EDITOR_PUBLISH = 'EDITOR_PUBLISH';
export const EDITOR_PUBLISHED = 'EDITOR_PUBLISHED';
export const TOGGLE_TOPBAR_NAVIGATION = 'EDITOR_TOGGLE_TOPBAR_NAVIGATION';
export const OPEN_CONFIRM_EXIT_EDITOR = 'OPEN_CONFIRM_EXIT_EDITOR';
export const CLOSE_CONFIRM_EXIT_EDITOR = 'CLOSE_CONFIRM_EXIT_EDITOR';
